# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
  name: Update README with my latest coding stats
  on:
    schedule:
      - cron: "30 5 * * *"

  jobs:
    update-Readme:
      name: Automatically update my README
      runs-on: ubuntu-latest
      steps:
        - uses: tariksahni/coding-stats-wakatime@v1.0.0
          with:
            WAKATIME_API_KEY: ${{ secrets.WAKA }}
            SHOW_MONTHLY: false
            GITHUB_TOKEN: ${{ github.token }}
            GITHUB_ACTION: ${{ github.action }}
